services:
  db:
    build:
      context: ./db
    shm_size: 128mb
    ports:
      - 5432:5432
    env_file:
      - ./.env 

  kc:
    container_name: kc
    depends_on:
      - db
    build:
      context: ./kc
    ports:
      - ${KC_HTTP_PORT}:${KC_HTTP_PORT}
      - ${KC_HTTP_MANAGEMENT_PORT}:${KC_HTTP_MANAGEMENT_PORT}
    env_file:
      - ./.env 
    command:
        - start-dev
        - --import-realm
    volumes:
      - ../scripts/keycloak-export:/opt/keycloak/data/import

  mailhog:
    depends_on:
      - kc
    build:
      context: ./mailhog
    ports:
      - ${MH_UI_BIND_ADDR_PORT}:${MH_UI_BIND_ADDR_PORT}
    env_file:
      - ./.env 

  api:
    depends_on:
      - kc
    build:
      context: ./api
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - ./.env 

  react:
    depends_on:
      - kc
      - api
    build:
      context: ./react
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    env_file:
      - ./.env 
    volumes:
      - ./react/src:/app/src:rw

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Example Org"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
      - "636:636"
    volumes:
       - ./ldif/50-bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif:ro
    command: --copy-service